FROM python:3.11-slim
WORKDIR /app

COPY app/frontend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/frontend/ ./app/frontend/

ENV MODEL_DIR=/app/data

EXPOSE 8501
CMD ["streamlit", "run", "app/frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]